---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - gym.k8s.gym
  resources:
  - questions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gym.k8s.gym
  resources:
  - questions/finalizers
  verbs:
  - update
- apiGroups:
  - gym.k8s.gym
  resources:
  - questions/status
  verbs:
  - get
  - patch
  - update
